# Generated by Django 5.1.2 on 2024-10-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_9d8241_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""INSERT INTO store_collection(title) values ('collection1')""","""DELETE FROM store_collection where title = ' collection1""")
    ]
