# Generated by Django 5.1.2 on 2024-11-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20241029_2340"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
    ]
